services:
  web:
    image: kvtodev/fcalendar:dev
    container_name: fcalendar
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=Fcalendar_backend.settings.settings_dev
      - DB_HOST=db
      - DB_NAME=fcalendar
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_PORT=5432
      - SECRET_KEY=k3it2tcb16gtacj83&06d4h
      - AMAP_API_KEY=3c224420b5589a8267dbf12fed5db087
      - MOONSHOT_API_KEY=sk-f6iWaYictJnifDoiLEYCvEvKsdrEKYFOzxYthpjgYyAfvqhl
    volumes:
      - ./media:/app/media

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: fcalendar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./data:/var/lib/postgresql/data
